void calib_dist_hvaldemlo()
{
//=========Macro generated from canvas: c1_n1/c1
//=========  (Fri Mar  3 00:55:06 2023) by ROOT version 6.24/00
   TCanvas *c1_n1 = new TCanvas("c1_n1", "c1",1,1,800,578);
   gStyle->SetOptStat(0);
   c1_n1->SetHighLightColor(2);
   c1_n1->Range(1.132833,-6.075949,1.455167,31.89873);
   c1_n1->SetFillColor(0);
   c1_n1->SetBorderMode(0);
   c1_n1->SetBorderSize(0);
   c1_n1->SetTickx(1);
   c1_n1->SetTicky(1);
   c1_n1->SetLeftMargin(0.14);
   c1_n1->SetRightMargin(0.14);
   c1_n1->SetTopMargin(0.05);
   c1_n1->SetBottomMargin(0.16);
   c1_n1->SetFrameBorderMode(0);
   c1_n1->SetFrameBorderMode(0);
   
   TH1D *hvaldemlo__8 = new TH1D("hvaldemlo__8","",15,1.17796,1.41004);
   hvaldemlo__8->SetBinContent(0,1);
   hvaldemlo__8->SetBinContent(1,1);
   hvaldemlo__8->SetBinContent(2,1);
   hvaldemlo__8->SetBinContent(4,21);
   hvaldemlo__8->SetBinContent(5,16);
   hvaldemlo__8->SetBinContent(6,6);
   hvaldemlo__8->SetMinimum(0);
   hvaldemlo__8->SetMaximum(30);
   hvaldemlo__8->SetEntries(47);
   hvaldemlo__8->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   hvaldemlo__8->SetLineColor(ci);
   hvaldemlo__8->SetLineWidth(2);
   hvaldemlo__8->SetMarkerStyle(20);
   hvaldemlo__8->SetMarkerSize(1.2);
   hvaldemlo__8->GetXaxis()->SetTitle("Mean Dem. Low-GainCIS Constant [ADC counts / pC]");
   hvaldemlo__8->GetXaxis()->CenterTitle(true);
   hvaldemlo__8->GetXaxis()->SetNdivisions(509);
   hvaldemlo__8->GetXaxis()->SetLabelFont(42);
   hvaldemlo__8->GetXaxis()->SetTitleOffset(1);
   hvaldemlo__8->GetXaxis()->SetTitleFont(42);
   hvaldemlo__8->GetYaxis()->SetTitle("Number of ADC Channels");
   hvaldemlo__8->GetYaxis()->SetNdivisions(305);
   hvaldemlo__8->GetYaxis()->SetLabelFont(42);
   hvaldemlo__8->GetYaxis()->SetTitleOffset(1.4);
   hvaldemlo__8->GetYaxis()->SetTitleFont(42);
   hvaldemlo__8->GetZaxis()->SetLabelFont(42);
   hvaldemlo__8->GetZaxis()->SetTitleOffset(1);
   hvaldemlo__8->GetZaxis()->SetTitleFont(42);
   hvaldemlo__8->Draw("");
   TLatex *   tex = new TLatex(0.18,0.865,"ATLAS");
tex->SetNDC();
   tex->SetTextFont(72);
   tex->SetTextSize(0.035);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.27,0.865,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.035);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.18,0.785,"Dem. Low-Gain");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.035);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.18,0.825,"Tile Calorimeter");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.035);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.18,0.745,"July 1 - December 1, 2022");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.035);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.59,0.865,"Mean  1.24");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.035);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.59,0.825,"RMS/Mean  1.44%");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.035);
   tex->SetLineWidth(2);
   tex->Draw();
   c1_n1->Modified();
   c1_n1->cd();
   c1_n1->SetSelected(c1_n1);
}
