void time_spread_rms()
{
//=========Macro generated from canvas: c1_n4/c1
//=========  (Fri Mar  3 00:55:01 2023) by ROOT version 6.24/00
   TCanvas *c1_n4 = new TCanvas("c1_n4", "c1",0,0,800,602);
   gStyle->SetOptStat(0);
   c1_n4->SetHighLightColor(2);
   c1_n4->Range(-0.2162162,-2.21519,1.135135,5.379747);
   c1_n4->SetFillColor(0);
   c1_n4->SetBorderMode(0);
   c1_n4->SetBorderSize(0);
   c1_n4->SetLogy();
   c1_n4->SetTickx(1);
   c1_n4->SetTicky(1);
   c1_n4->SetLeftMargin(0.16);
   c1_n4->SetTopMargin(0.05);
   c1_n4->SetBottomMargin(0.16);
   c1_n4->SetFrameBorderMode(0);
   c1_n4->SetFrameBorderMode(0);
   
   TH1F *lowmIgain__1 = new TH1F("lowmIgain__1","",20,0,1);
   lowmIgain__1->SetBinContent(1,9527);
   lowmIgain__1->SetBinContent(2,64);
   lowmIgain__1->SetBinContent(3,8);
   lowmIgain__1->SetBinContent(4,1);
   lowmIgain__1->SetBinContent(5,2);
   lowmIgain__1->SetBinContent(8,1);
   lowmIgain__1->SetBinContent(9,2);
   lowmIgain__1->SetBinContent(10,1);
   lowmIgain__1->SetBinContent(11,1);
   lowmIgain__1->SetBinContent(15,1);
   lowmIgain__1->SetBinContent(16,2);
   lowmIgain__1->SetBinContent(18,1);
   lowmIgain__1->SetBinContent(19,1);
   lowmIgain__1->SetBinContent(21,111);
   lowmIgain__1->SetMinimum(0.1);
   lowmIgain__1->SetMaximum(100000);
   lowmIgain__1->SetEntries(9723);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#0000ff");
   lowmIgain__1->SetLineColor(ci);
   lowmIgain__1->SetLineWidth(2);
   lowmIgain__1->SetMarkerStyle(20);
   lowmIgain__1->SetMarkerSize(1.2);
   lowmIgain__1->GetXaxis()->SetTitle("CIS Calibration RMS / Mean [%]");
   lowmIgain__1->GetXaxis()->SetNdivisions(509);
   lowmIgain__1->GetXaxis()->SetLabelFont(42);
   lowmIgain__1->GetXaxis()->SetTitleOffset(1);
   lowmIgain__1->GetXaxis()->SetTitleFont(42);
   lowmIgain__1->GetYaxis()->SetTitle("Number of ADC Channels");
   lowmIgain__1->GetYaxis()->SetNdivisions(305);
   lowmIgain__1->GetYaxis()->SetLabelFont(42);
   lowmIgain__1->GetYaxis()->SetTitleOffset(1);
   lowmIgain__1->GetYaxis()->SetTitleFont(42);
   lowmIgain__1->GetZaxis()->SetLabelFont(42);
   lowmIgain__1->GetZaxis()->SetTitleOffset(1);
   lowmIgain__1->GetZaxis()->SetTitleFont(42);
   lowmIgain__1->Draw("");
   
   TH1F *highmIgain__2 = new TH1F("highmIgain__2","",20,0,1);
   highmIgain__2->SetBinContent(1,9542);
   highmIgain__2->SetBinContent(2,74);
   highmIgain__2->SetBinContent(3,14);
   highmIgain__2->SetBinContent(4,7);
   highmIgain__2->SetBinContent(5,3);
   highmIgain__2->SetBinContent(6,4);
   highmIgain__2->SetBinContent(7,3);
   highmIgain__2->SetBinContent(8,2);
   highmIgain__2->SetBinContent(9,1);
   highmIgain__2->SetBinContent(13,1);
   highmIgain__2->SetBinContent(16,1);
   highmIgain__2->SetBinContent(17,1);
   highmIgain__2->SetBinContent(19,3);
   highmIgain__2->SetBinContent(21,67);
   highmIgain__2->SetMinimum(0.1);
   highmIgain__2->SetMaximum(100000);
   highmIgain__2->SetEntries(9723);

   ci = TColor::GetColor("#ff0000");
   highmIgain__2->SetLineColor(ci);
   highmIgain__2->SetLineStyle(2);
   highmIgain__2->SetLineWidth(2);
   highmIgain__2->SetMarkerStyle(20);
   highmIgain__2->SetMarkerSize(1.2);
   highmIgain__2->GetXaxis()->SetTitle("CIS Calibration RMS / Mean [%]");
   highmIgain__2->GetXaxis()->SetNdivisions(509);
   highmIgain__2->GetXaxis()->SetLabelFont(42);
   highmIgain__2->GetXaxis()->SetTitleOffset(1);
   highmIgain__2->GetXaxis()->SetTitleFont(42);
   highmIgain__2->GetYaxis()->SetTitle("Number of ADC Channels");
   highmIgain__2->GetYaxis()->SetNdivisions(305);
   highmIgain__2->GetYaxis()->SetLabelFont(42);
   highmIgain__2->GetYaxis()->SetTitleOffset(1);
   highmIgain__2->GetYaxis()->SetTitleFont(42);
   highmIgain__2->GetZaxis()->SetLabelFont(42);
   highmIgain__2->GetZaxis()->SetTitleOffset(1);
   highmIgain__2->GetZaxis()->SetTitleFont(42);
   highmIgain__2->Draw("SAME");
   TLatex *   tex = new TLatex(0.6,0.88," HG Mean       0.13%");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.032);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.6,0.84," HG RMS        1.46%");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.032);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.6,0.8," LG Mean        0.22%");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.032);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.6,0.76," LG RMS         2.06%");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.032);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TLegend *leg = new TLegend(0.6,0.5,0.7,0.6,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.032);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("demonstrator"," High Gain","l");

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("demonstratorlo"," Low Gain","l");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
      tex = new TLatex(0.22,0.863,"ATLAS");
tex->SetNDC();
   tex->SetTextFont(72);
   tex->SetTextSize(0.035);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.31,0.863,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.035);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.22,0.807,"Tile Calorimeter");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.035);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.22,0.751,"July 1 - December 1, 2022");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.035);
   tex->SetLineWidth(2);
   tex->Draw();
   c1_n4->Modified();
   c1_n4->cd();
   c1_n4->SetSelected(c1_n4);
}
