#!/usr/bin/env python
# Original Author: Christopher Tunnell <tunnell@hep.uchicago.edu> June 20, 2009
# Adapted from CalibDist macro by Brendan Haas (Aug 17th 2011)
#
# This macro makes 8 plots (for each gain for each partition) that shows the 
# CIS constant values for each module and channel. This plot is closely related
# to the one generated by CalibChan.py.
#

import os
os.chdir(os.getenv('TUCS','.'))
exec(open('src/load.py').read(), globals()) # don't remove this!

runs = '-28 day' # Use the last month of runs if '-4 week' or '28 day'

#runs = [183009,183166,183367,183558,183591,183719,183767,183785,183855,183860,183945,184313,184315] #June 2011
#runs = [183009,183166,183367] #Short list of runs from June 2011 for testing
#runs = [90555,90555,90860,91315,91567,91837,92016,92416,92971,92972] # novem 08
#runs = [183009, 183591, 184313] #Short list of runs for testing purposes

Go([
    Use(run=runs, runType='CIS'),      # Tell TUCS to use CIS runs, and which runs
    ReadCIS(),                         # Read in CIS constants and quality flags
    #ReadDB(),                          # Read in constants from COOL DB
    CISRecalibrateProcedure(all=True), # Run calibration procedure
    CISConstantRegions(),              # Generate CIS Constant Region plots 
    ])

