void history()
{
//=========Macro generated from canvas: c1_n1/c1
//=========  (Fri Mar  3 00:35:45 2023) by ROOT version 6.24/00
   TCanvas *c1_n1 = new TCanvas("c1_n1", "c1",0,0,800,602);
   gStyle->SetOptStat(0);
   c1_n1->SetHighLightColor(2);
   c1_n1->Range(-4.166667,-1.304327,4.166667,4.966277);
   c1_n1->SetFillColor(0);
   c1_n1->SetBorderMode(0);
   c1_n1->SetBorderSize(0);
   c1_n1->SetLogy();
   c1_n1->SetTickx(1);
   c1_n1->SetTicky(1);
   c1_n1->SetLeftMargin(0.14);
   c1_n1->SetRightMargin(0.14);
   c1_n1->SetBottomMargin(0.16);
   c1_n1->SetFrameBorderMode(0);
   c1_n1->SetFrameBorderMode(0);
   
   TH1F *Statistics__1 = new TH1F("Statistics__1","",100,-3,3);
   Statistics__1->SetBinContent(17,1);
   Statistics__1->SetBinContent(30,1);
   Statistics__1->SetBinContent(34,2);
   Statistics__1->SetBinContent(35,2);
   Statistics__1->SetBinContent(41,1);
   Statistics__1->SetBinContent(42,2);
   Statistics__1->SetBinContent(43,2);
   Statistics__1->SetBinContent(44,1);
   Statistics__1->SetBinContent(45,2);
   Statistics__1->SetBinContent(46,1);
   Statistics__1->SetBinContent(47,2);
   Statistics__1->SetBinContent(48,6);
   Statistics__1->SetBinContent(49,87);
   Statistics__1->SetBinContent(50,13316);
   Statistics__1->SetBinContent(51,5774);
   Statistics__1->SetBinContent(52,92);
   Statistics__1->SetBinContent(53,11);
   Statistics__1->SetBinContent(54,7);
   Statistics__1->SetBinContent(55,1);
   Statistics__1->SetBinContent(56,2);
   Statistics__1->SetBinContent(59,1);
   Statistics__1->SetBinContent(60,1);
   Statistics__1->SetBinContent(62,1);
   Statistics__1->SetBinContent(85,1);
   Statistics__1->SetBinContent(88,1);
   Statistics__1->SetBinContent(90,1);
   Statistics__1->SetBinContent(96,2);
   Statistics__1->SetEntries(19323);
   Statistics__1->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   Statistics__1->SetLineColor(ci);
   Statistics__1->SetLineWidth(2);
   Statistics__1->SetMarkerStyle(20);
   Statistics__1->SetMarkerSize(1.2);
   Statistics__1->GetXaxis()->SetTitle("Variation of ADC Calibration Constants [%]");
   Statistics__1->GetXaxis()->CenterTitle(true);
   Statistics__1->GetXaxis()->SetNdivisions(509);
   Statistics__1->GetXaxis()->SetLabelFont(42);
   Statistics__1->GetXaxis()->SetTitleOffset(1);
   Statistics__1->GetXaxis()->SetTitleFont(42);
   Statistics__1->GetYaxis()->SetTitle("Number of ADC Channels");
   Statistics__1->GetYaxis()->CenterTitle(true);
   Statistics__1->GetYaxis()->SetNdivisions(305);
   Statistics__1->GetYaxis()->SetLabelFont(42);
   Statistics__1->GetYaxis()->SetTitleOffset(1.45);
   Statistics__1->GetYaxis()->SetTitleFont(42);
   Statistics__1->GetZaxis()->SetLabelFont(42);
   Statistics__1->GetZaxis()->SetTitleOffset(1);
   Statistics__1->GetZaxis()->SetTitleFont(42);
   Statistics__1->Draw("");
   TLatex *   tex = new TLatex(0.16,0.85,"ATLAS");
tex->SetNDC();
   tex->SetTextFont(72);
   tex->SetTextSize(0.035);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.85,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.035);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16,0.795,"Tile Calorimeter");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.035);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16,0.74,"Run 3: July v. November, 2022");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.035);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.66,0.84,"Mean     -0.011%");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.035);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.66,0.795,"RMS      0.055%");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.035);
   tex->SetLineWidth(2);
   tex->Draw();
   c1_n1->Modified();
   c1_n1->cd();
   c1_n1->SetSelected(c1_n1);
}
